server:
  port: 3022

spring:
  application:
    name: cloud-video-clips
  redis:
    redisson:
      config: | 
        singleServerConfig:
          address: redis://127.0.0.1:6314
          password: 
          database: 0

oss:
  enable: false
  accessKey: 
  accessSecret: 
  endpoint: 
  region: 
  bucketName: 
  perFileMaxSize: 50M

vc:
  tmpDir: /tmp
  localRoot:
